### PR TITLE
updated to use latest versions of libzmq/czmq

### PR DESCRIPTION
**Pull request by sgluss**

### CODE REVIEW

**Comment by bluca** [comment]
Sorry but not sure how this can actually work... You are changing a prototype and a call, without changing the actual function definition. And there are still a LOT of API calls that are no longer there in CZMQ 4, like zthread.

**Comment by sgluss** [comment]
ah you're right, looking again I think I've lost some of my changes. It involved replacing zthread usage with zactor... should I close this PR for now?

also, is updating ZWSSock to be compatible with CZMQ4 a reasonable thing to do?

**Comment by bluca** [comment]
Yes, updating is the right thing to do, thanks for taking care of it!
Using zactor in lieu of zthread is also the right replacement. Feel free to keep the PR open and to force push the other changes.

**Comment by pedromellofh** [comment]
it's been a while since the last comment on this subject, but I made some extra work upon sgluss' patch and it's now building against last czmq (which is 4.1.1 for now). 
[czmq4fix.patch.txt](https://github.com/zeromq/zwssock/files/1932208/czmq4fix.patch.txt)

**Comment by somdoron** [comment]
Can you make a different pull request?

**Comment by sgluss** [comment]
nice one pedro! I'll help test it in windows

**Comment by pedromellofh** [comment]
just created a new pull request... it's sgluss' patch plus mine adjustments. I have made some code parity with NetMQ implementation too

**Comment by bluca** [comment]
closing for https://github.com/zeromq/zwssock/pull/20

**Pull request closed without merging**
