### PR TITLE
Hotfix moreframes

### LINKED ISSUE #9: Assert (!more)
At this moment multipart messages containing more than one frame cause the library to assert, unless asserting is disabled of course. What was the reason for the assert?

https://github.com/zeromq/zwssock/blob/master/src/CZMQ-ZWSSock/zwssock.c#L185

### PR DESCRIPTION
**Pull request by skinkie**
This branch fixes #9 

Please do not blindly merge this pull request. It changes something **significantly** in the code, for ea199e9 and I might not have understood why it was solved in the way it was.

### CODE REVIEW

**Comment by somdoron** [comment]
@skinkie I made you a maintainer on the zwssock project. 

Make sure to read https://rfc.zeromq.org/spec:42/C4

Reviewing the PR now..

**Comment by somdoron** [comment]
@skinkie does this PR backwards compatible? did the protocol changed?

**Comment by somdoron** [comment]
ignore my last comment, code seems fine, merging.

**Comment by skinkie** [comment]
@somdoron could you maybe explain why the previous code was so _difficult_? Maybe the decoder wanted to make the more frame transparent to the layer below, but it had quite some overhead.

**Comment by bluca** [comment]
@skinkie now that you are a maintainer and have write access, could you please enable 2-factor authentication on Github? Thanks!

**Comment by skinkie** [comment]
@bluca thanks for the reminder, I have just set it up. I typically only use the ssh keys stuff to push, so I couldn't really bother before.

**Pull request merged**
